### ISSUE TITLE
Non-ASCII character '\xc3' in file fuxploider/UploadForm.py on line 49, but no encoding 

### ISSUE THREAD

**Issue by Shiva108** [almandin/fuxploider#11]
I added "# -*- coding: UTF-8 -*-" but no success:

──╼ #python ./fuxploider.py 
Traceback (most recent call last):
  File "./fuxploider.py", line 5, in <module>
    import UploadForm
  File "/home/e/Auto/fuxploider/UploadForm.py", line 49
SyntaxError: Non-ASCII character '\xc3' in file fuxploider/UploadForm.py on line 49, but no encoding declared; see http://python.org/dev/peps/pep-0263/ for details

**Comment by almandin** [comment]
your issue should be gone with the last commit. It was due to a french comment in the code, using accented characters ;)
git pull/clone and try again :)
