### ISSUE TITLE
OSX - requirements - FIXED

### ISSUE THREAD

**Issue by Kaicastledine** [almandin/fuxploider#2]
To get working on OSX need to include the following,

Error after pip3 install with requirements

```
KCMP:fuxploider kaic$ python fuxploider.py -h
Traceback (most recent call last):
  File "fuxploider.py", line 2, in <module>
    import re,requests,argparse,logging,os,coloredlogs,datetime,getpass,tempfile,itertools,json,concurrent.futures
ImportError: No module named coloredlogs
```

FIX

` sudo pip install coloredlogs`

Then use python3

```
KCMP:fuxploider kaic$ python3 fuxploider.py -h
usage: fuxploider.py [-h] [-d postData] [--proxy proxyUrl]
                     [--proxy-creds [credentials]] [-f integer]
                     [--cookies omnomnom] [--uploads-path path]
                     [-t templateName] [-r regex] -u target
                     [--not-regex regex] [--true-regex regex]
                     [-l listOfExtensions | -n n] [-v | -vv | -vvv] [-s] [-y]
                     [-T Threads]

```

**Comment by almandin** [comment]
Your `python` command may lead to the python2 binary and not the python3 one. This way, you installed dependencies for python3 and then use the soft with python2.
The easiest way to be sure that you set up everything correctly correctly is to use pip3 and python3 binaries directly.

**Comment by Kaicastledine** [comment]
Wiki said to use python not python3 and pip3. 
Works perfectly now, thanks for the dev on this tool :)
