### ISSUE TITLE
Warning

### ISSUE THREAD

**Issue by kirtiso** [almandin/fuxploider#20]
Hello sir,
[*] starting at 17:02:24
C:\Users\user\AppData\Local\Programs\Python\Python37\lib\site-packages\urllib3\connectionpool.py:847: InsecureRequestWarning: Unverified HTTPS request is being made. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#ssl-warnings
  InsecureRequestWarning)
2018-11-12 17:02:31 CRITICAL - No HTML forms found.

E:\wpt2\fuxploider-master>pip install urllib3[secure]
Requirement already satisfied: urllib3[secure] in c:\python27\lib\site-packages (1.23)
Requirement already satisfied: idna>=2.0.0; python_version <= "2.7" and extra == "secure" in c:\python27\lib\site-packages (from urllib3[secure]) (2.7)
Requirement already satisfied: ipaddress; python_version <= "2.7" and extra == "secure" in c:\python27\lib\site-packages (from urllib3[secure]) (1.0.22)
Requirement already satisfied: pyOpenSSL>=0.14; python_version == "2.7" and extra == "secure" in c:\python27\lib\site-packages (from urllib3[secure]) (18.0.0)
Requirement already satisfied: certifi; extra == "secure" in c:\python27\lib\site-packages (from urllib3[secure]) (2018.8.24)
Requirement already satisfied: cryptography>=1.3.4; python_version <= "2.7" and extra == "secure" in c:\python27\lib\site-packages (from urllib3[secure]) (2.3.1)
Requirement already satisfied: six>=1.5.2 in c:\python27\lib\site-packages (from pyOpenSSL>=0.14; python_version == "2.7" and extra == "secure"->urllib3[secure]) (1.11.0)
Requirement already satisfied: cffi!=1.11.3,>=1.7 in c:\python27\lib\site-packages (from cryptography>=1.3.4; python_version <= "2.7" and extra == "secure"->urllib3[secure]) (1.11.5)
Requirement already satisfied: enum34; python_version < "3" in c:\python27\lib\site-packages (from cryptography>=1.3.4; python_version <= "2.7" and extra == "secure"->urllib3[secure]) (1.1.6)
Requirement already satisfied: asn1crypto>=0.21.0 in c:\python27\lib\site-packages (from cryptography>=1.3.4; python_version <= "2.7" and extra == "secure"->urllib3[secure]) (0.24.0)
Requirement already satisfied: pycparser in c:\python27\lib\site-packages (from cffi!=1.11.3,>=1.7->cryptography>=1.3.4; python_version <= "2.7" and extra == "secure"->urllib3[secure]) (2.19)

still have same issue.Please help how can i resolve it???

**Comment by almandin** [comment]
Everything looks fine, you just have an ssl warning because of doing insecure https requests but the program still works. The critical log states that fuxploider was unable to find upload forms on the page you are attacking.

**Comment by johanych** [comment]
Hi, I'm getting this error:

File "fuxploider.py", line 175
    print(f"[*] starting at {now.strftime('%H:%M:%S')}")
                                                      ^
SyntaxError: invalid syntax

**Comment by almandin** [comment]
Fixed by dc3bd1bef902ea22fe8271256da479ad99c3688e.
