### ISSUE TITLE
TypeError when uploading payloads

### ISSUE THREAD

**Issue by JamesK852** [almandin/fuxploider#22]
OS: Kali 2018

When trying to run the script I successfully identify multiple file types but when I confirm to upload payloads I get this error

`Traceback (most recent call last):
  File "fuxploider.py", line 298, in <module>
    with open(os.path.join((templatesFolder, template["filename"])), "rb") as templatefd:
  File "/usr/lib/python3.6/posixpath.py", line 80, in join
    a = os.fspath(a)
TypeError: expected str, bytes or os.PathLike object, not tuple
`

If I get this error using docker image on the same host

`Start uploading payloads? [Y/n]: Traceback (most recent call last):
  File "fuxploider.py", line 278, in <module>
    cont = input("Start uploading payloads? [Y/n]: ")
EOFError: EOF when reading a line
`

**Comment by fscamuzzi2** [comment]
same for me on docker! 👍 

Traceback (most recent call last):
  File "fuxploider.py", line 298, in <module>
    with open(os.path.join((templatesFolder, template["filename"])), "rb") as templatefd:
  File "/usr/local/lib/python3.6/posixpath.py", line 80, in join
    a = os.fspath(a)
TypeError: expected str, bytes or os.PathLike object, not tuple

**Comment by abuvanth** [comment]
same 

Traceback (most recent call last):
  File "fuxploider.py", line 298, in <module>
    with open(os.path.join((templatesFolder, template["filename"])), "rb") as templatefd:
  File "/usr/lib/python3.6/posixpath.py", line 80, in join
    a = os.fspath(a)
TypeError: expected str, bytes or os.PathLike object, not tuple

**Comment by TimV01** [comment]
Bump.. also got this issue @almandin 

How to reproduce: just use the program and the error appears after you start code execution detection.

**Comment by almandin** [comment]
A fix has been pushed to the **_dev_** branch, can you test it and tell me if it works please ? I will merge it to master if it appears to work.

**Comment by TimV01** [comment]
It works, you can merge it. Thanks for the fix @almandin

**Comment by almandin** [comment]
@keethesh fixed it :-) I merge to master.
