### ISSUE TITLE
Print issue

### ISSUE THREAD

**Issue by johanych** [almandin/fuxploider#24]
Hi, I'm getting this error. I'm running with python3 (3.5.1)

```
File "fuxploider.py", line 175
    print(f"[*] starting at {now.strftime('%H:%M:%S')}")
                                                      ^
SyntaxError: invalid syntax
```

**Comment by almandin** [comment]
You need at least python 3.6.
I will update the docs and the "python" logo on the readme to state this clearly, sorry :x

**Comment by johanych** [comment]
Thank you very much for your time.
I already fix it. Great tool.

Regards

Johanny


On Feb 27, 2019, at 3:58 PM, Virgile Jarry <notifications@github.com<mailto:notifications@github.com>> wrote:


You need at least python 3.6.
I will update the docs and the "python" logo on the readme to state this clearly, sorry :x
